name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint & Format
    uses: ./.github/workflows/lint.yml

  test:
    name: Unit Tests
    uses: ./.github/workflows/test.yml

  e2e:
    name: E2E Tests
    uses: ./.github/workflows/e2e.yml
    needs: [lint, test]

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: [lint, test, e2e]
